ARG REPOSITORY
ARG IMAGE
ARG CP_VERSION

FROM $REPOSITORY/$IMAGE:$CP_VERSION

USER root
RUN yum install -y \
     libmnl \
     findutils \
     which
RUN uname -a
RUN rpm -i --nodeps --nosignature http://vault.centos.org/8.1.1911/BaseOS/aarch64/os/Packages/iproute-tc-4.18.0-15.el8.aarch64.rpm
RUN rpm -i --nodeps --nosignature http://vault.centos.org/8.1.1911/BaseOS/aarch64/os/Packages/iptables-libs-1.8.2-16.el8.aarch64.rpm
USER appuser
